/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {}

export interface components {
  schemas: {
    CreateCollectionItemView: {
      webSocketUrl?: components["schemas"]["WebSocketUrl"];
      /**
       * @description The secret seed of collection's requester. May be provided in the mnemonic or hexadecimal form.
       * @example used route main sock exotic mule screen whale dance tail ladder lift
       */
      suri?: string;
      itemId?: components["schemas"]["ItemId"];
      itemDescription?: components["schemas"]["ItemDescription"];
    };
    GetCollectionItemView: {
      webSocketUrl?: components["schemas"]["WebSocketUrl"];
    };
    /**
     * @description The WebSocket endpoint of a logion chain
     * @example wss://test-rpc01.logion.network
     */
    WebSocketUrl: string;
    /**
     * @description The unique identifier of the item in the collection e.g. the hex representation of a file's SHA256 hash.
     * @example 0xc3e49c87aa19ec987501fc2e207f5928bd31ee948f69455c733416564da158c5
     */
    ItemId: string;
    /**
     * @description A string describing the item. The string must be at most 4096 UTF-8 encoded bytes long.
     * @example NFT #1
     */
    ItemDescription: string;
    CollectionItemView: {
      /**
       * @description The Collection LOC's unique identifier.
       * @example 292327117366451619588297997097238907467
       */
      collectionLocId?: string;
      itemId?: components["schemas"]["ItemId"];
      itemDescription?: components["schemas"]["ItemDescription"];
    };
    ErrorMetadataView: {
      /**
       * @description The name of the pallet which emitted the error. May be undefined if call was not dispatched.
       * @example logionLoc
       */
      pallet?: string;
      /**
       * @description The error type. May be undefined if call was not dispatched.
       * @example CollectionItemAlreadyExists
       */
      error?: string;
      /**
       * @description Additional information about the error.
       * @example An item with same identifier already exists in the collection
       */
      details?: string;
    };
  };
}

export interface operations {}

export interface external {}
